
version: '3'
services:
  chirp-docker-gw:
    build: .
    ports:
      - "1700:1700/udp"
    devices:
      - /dev/ttyACM0
    volumes:
      - /home/pi/picogw/data:/gateway/lora_pkt_fwd/data
    network_mode: "bridge"
    restart: "unless-stopped"
  chirp-relay-gw:
    build: .
    ports:
      - "1701:1701/udp"
    devices:
      - /dev/ttyACM1:/dev/ttyACM0
    volumes:
      - /home/pi/picogw/data_relay:/gateway/lora_pkt_fwd/data
    network_mode: "bridge"
    restart: "unless-stopped"
volumes:
  data:    
